version: '2'

services:
  nginx:
    container_name: nginx
    build:
      context: docker/config/nginx
    volumes:
      - ./:/var/www
    ports:
      - "3000:80"
    links:
      - auth
      - content
    networks:
      - appnet

## Auth Microservice
  auth:
    container_name: auth
    env_file: '.env'
    build:
      context: docker/auth
    volumes:
      - ./auth:/var/www
    links:
      - db
    networks:
      - appnet
  db:
    container_name: auth_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dockerApp
    ports:
      - "33061:3306"
    networks:
      - appnet

  ## Auth Microservice
  content:
    container_name: content
    env_file: '.env'
    build:
      context: docker/content
    volumes:
      - ./content:/var/www
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"